// Copyright 2021-present The Atlas Authors. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

//go:build ignore

package main

import (
	_ "embed"
	"log"

	"entgo.io/ent/entc"
	"entgo.io/ent/entc/gen"
)

//go:embed templates.tmpl
var tpls string

func main() {
	err := entc.Generate("./schema", &gen.Config{
		Header: `// Copyright 2021-present The Atlas Authors. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by entc, DO NOT EDIT.
`,
		Features:  []gen.Feature{gen.FeatureUpsert, gen.FeatureExecQuery, gen.FeatureSchemaConfig},
		Templates: []*gen.Template{gen.MustParse(gen.NewTemplate("client/init").Parse(tpls))},
	})
	if err != nil {
		log.Fatalf("running ent codegen: %v", err)
	}
}
