run:
  timeout: 3m

issues:
  include:
    - EXC0012
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
    - path: sql/migrate/dir.go
      linters:
        - gosec
    - path: sql/migrate/lex.go
      linters:
        - revive

linters-settings:
  goheader:
    template: |-
      Copyright 2021-present The Atlas Authors. All rights reserved.
      This source code is licensed under the Apache 2.0 license found
      in the LICENSE file in the root directory of this source tree.

linters:
  disable-all: true
  enable:
    - gosec
    - revive
    - goheader
