run:
  timeout: 3m

issues:
  include:
    - EXC0012
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
    - path: sql/migrate/migrate.go
      linters:
        - gosec

linters:
  disable-all: true
  enable:
    - gosec
    - revive
