// Copyright 2021-present The Atlas Authors. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

package postgres

import "ariga.io/atlas/sql/schema"

// crdbDiff decorates PostgreSQL diff.
type crdbDiff struct{ diff }

// SchemaAttrDiff returns a changeset for migrating schema attributes from one state to the other.
func (cd *crdbDiff) SchemaAttrDiff(from, to *schema.Schema) []schema.Change {
	return cd.diff.SchemaAttrDiff(from, to)
}

// TableAttrDiff returns a changeset for migrating table attributes from
func (cd *crdbDiff) TableAttrDiff(from, to *schema.Table) ([]schema.Change, error) {
	return cd.diff.TableAttrDiff(from, to)
}

// ColumnChange returns the schema changes (if any) for migrating one column to the other.
func (cd *crdbDiff) ColumnChange(from, to *schema.Column) (schema.ChangeKind, error) {
	return cd.diff.ColumnChange(from, to)
}

// IndexAttrChanged reports if the index attributes were changed.
func (cd *crdbDiff) IndexAttrChanged(from, to []schema.Attr) bool {
	return cd.diff.IndexAttrChanged(from, to)
}

// IndexPartAttrChanged reports if the index-part attributes were
func (cd *crdbDiff) IndexPartAttrChanged(from, to *schema.IndexPart) bool {
	return cd.diff.IndexPartAttrChanged(from, to)
}

// IsGeneratedIndexName reports if the index name was generated by the database
func (cd *crdbDiff) IsGeneratedIndexName(t *schema.Table, i *schema.Index) bool {
	return cd.diff.IsGeneratedIndexName(t, i)
}

// ReferenceChanged reports if the foreign key referential action was
func (cd *crdbDiff) ReferenceChanged(from, to schema.ReferenceOption) bool {
	return cd.diff.ReferenceChanged(from, to)
}
