// Copyright 2021-present The Atlas Authors. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in ariga.io/atlas/cmd/atlas/internal/migrate/ent/runtime.go

const (
	Version = "v0.12.5-0.20231113103531-9aba4ae091d1"           // Version of ent codegen.
	Sum     = "h1:b+pptFMbxbDfAMmTQZ8SiFq92mld0iw+kXf3toC/qbI=" // Sum of ent codegen.
)
