// Copyright 2021-present The Atlas Authors. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in ariga.io/atlas/cmd/atlas/internal/migrate/ent/runtime.go

const (
	Version = "v0.11.9-0.20230214130636-4e05f767170e"           // Version of ent codegen.
	Sum     = "h1:hq9hlXxX563oK0V1rjOm6wmiU06CGaXqaLMbwDFd7fM=" // Sum of ent codegen.
)
