// Copyright 2021-present The Atlas Authors. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

//go:build !ent

package ydb

import (
	"fmt"
	"reflect"

	"ariga.io/atlas/sql/internal/sqlx"
	"ariga.io/atlas/sql/schema"
)

// DefaultDiff provides basic diffing capabilities for YDB dialect.
// Note, it is recommended to call Open, create a new Driver and use its
// Differ when a database connection is available.
var DefaultDiff schema.Differ = &sqlx.Diff{
	DiffDriver: &diff{&conn{ExecQuerier: sqlx.NoRows}},
}

// A diff provides a YDB implementation for sqlx.DiffDriver.
type diff struct {
	*conn
}

// RealmObjectDiff returns a changeset for migrating realm (database) objects
// from one state to the other.
func (*diff) RealmObjectDiff(_, _ *schema.Realm) ([]schema.Change, error) {
	return nil, nil // unimplemented
}

// SchemaAttrDiff returns a changeset for migrating schema attributes from one state to the other.
func (*diff) SchemaAttrDiff(_, _ *schema.Schema) []schema.Change {
	// No special schema attribute diffing for YDB.
	return nil
}

// SchemaObjectDiff returns a changeset for migrating schema objects from
// one state to the other.
func (*diff) SchemaObjectDiff(_, _ *schema.Schema, _ *schema.DiffOptions) ([]schema.Change, error) {
	// YDB doesn't have schema-level objects like enums or sequences
	return nil, nil
}

// TableAttrDiff returns a changeset for migrating table attributes from one state to the other.
func (d *diff) TableAttrDiff(
	from *schema.Table,
	to *schema.Table,
	opts *schema.DiffOptions,
) ([]schema.Change, error) {
	return sqlx.CheckDiffMode(from, to, opts.Mode), nil
}

// ViewAttrChanges returns schema changes for migrating view attributes.
func (*diff) ViewAttrChanges(_, _ *schema.View) []schema.Change {
	return nil // unimplemented.
}

// ColumnChange returns the schema changes (if any) for migrating one column to the other.
func (d *diff) ColumnChange(
	_ *schema.Table,
	from *schema.Column,
	to *schema.Column,
	_ *schema.DiffOptions,
) (schema.Change, error) {
	var change schema.ChangeKind
	if from.Type.Null != to.Type.Null {
		change |= schema.ChangeNull
	}

	changed, err := d.typeChanged(from, to)
	if err != nil {
		return sqlx.NoChange, err
	}
	if changed {
		change |= schema.ChangeType
	}

	if d.defaultChanged(from, to) {
		change |= schema.ChangeDefault
	}

	if change.Is(schema.NoChange) {
		return sqlx.NoChange, nil
	}

	return &schema.ModifyColumn{
		Change: change,
		From:   from,
		To:     to,
	}, nil
}

// typeChanged reports if the column type was changed.
func (d *diff) typeChanged(from *schema.Column, to *schema.Column) (bool, error) {
	fromType, toType := from.Type.Type, to.Type.Type
	if fromType == nil || toType == nil {
		return false, fmt.Errorf("ydb: missing type information for column %q", from.Name)
	}

	if reflect.TypeOf(fromType) != reflect.TypeOf(toType) {
		return true, nil
	}

	type1, err := FormatType(fromType)
	if err != nil {
		return false, err
	}

	type2, err := FormatType(toType)
	if err != nil {
		return false, err
	}
	return type1 != type2, nil
}

// defaultChanged reports if the default value of a column was changed.
func (d *diff) defaultChanged(from *schema.Column, to *schema.Column) bool {
	default1, ok1 := sqlx.DefaultValue(from)
	default2, ok2 := sqlx.DefaultValue(to)
	if ok1 != ok2 {
		return true
	}
	return default1 != default2
}

// IndexAttrChanged reports if the index attributes were changed.
func (*diff) IndexAttrChanged(from, to []schema.Attr) bool {
	var fromAttrs, toAttrs IndexAttributes
	sqlx.Has(from, &fromAttrs)
	sqlx.Has(to, &toAttrs)

	if fromAttrs.Async != toAttrs.Async {
		return true
	}

	if len(fromAttrs.CoverColumns) != len(toAttrs.CoverColumns) {
		return true
	}

	for i := range fromAttrs.CoverColumns {
		if fromAttrs.CoverColumns[i].Name != toAttrs.CoverColumns[i].Name {
			return true
		}
	}
	return false
}

// IndexPartAttrChanged reports if the index-part attributes were changed.
func (*diff) IndexPartAttrChanged(_, _ *schema.Index, _ int) bool {
	// YDB doesn't have per-part attributes like collation, prefix, or operator classes.
	return false
}

// IsGeneratedIndexName reports if the index name was generated by the database.
func (d *diff) IsGeneratedIndexName(_ *schema.Table, _ *schema.Index) bool {
	// YDB doesn't generate index names automatically.
	return false
}

// ReferenceChanged reports if the foreign key referential action was changed.
func (*diff) ReferenceChanged(_, _ schema.ReferenceOption) bool {
	// YDB doesn't support foreign keys.
	return false
}

// ForeignKeyAttrChanged reports if any of the foreign-key attributes were changed.
func (*diff) ForeignKeyAttrChanged(_, _ []schema.Attr) bool {
	// YDB doesn't support foreign keys.
	return false
}
