name: Build Docker
on:
  pull_request:
  push:
    branches:
      - master

env:
  CRDB_VERSIONS: v21.2.11 v22.1.0

jobs:
  build-services:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: "build cockroach image"
        run: |
          VER="${{ env.CRDB_VERSIONS }}"
          for i in $VER
          do
            :
            if ! docker manifest inspect ghcr.io/ariga/cockroachdb-single-node:$i; then
              go run internal/ci/cockroach/main.go $i > internal/ci/cockroach/Dockerfile
              docker build -t ghcr.io/ariga/cockroachdb-single-node:$i internal/ci/cockroach/
              docker push ghcr.io/ariga/cockroachdb-single-node:$i
            else
              echo image already exists
            fi
          done