name: CD - Build Docker - MySQL Quick Boot - Community Edition
on:
  push:
    paths:
      - .github/ops/mysql/**
      - .github/workflows/cd-docker-push-mysql_oss.yaml
    branches:
      - master
  schedule:
    # Runs at 00:00 on Sunday
    - cron: '0 0 * * 0'
  workflow_dispatch:
jobs:
  push-docker:
    strategy:
      fail-fast: false
      matrix:
        include:
          - dialect: mysql:latest
          - dialect: mysql:5.6
            platforms: linux/amd64
          - dialect: mysql:5.6.35
            platforms: linux/amd64
          - dialect: mysql:5.7
            platforms: linux/amd64
          - dialect: mysql:5.7.26
            platforms: linux/amd64
          - dialect: mysql:8
          - dialect: mariadb:latest
            build-args: SERVER=mariadbd
          - dialect: mariadb:10.2
          - dialect: mariadb:10.2.32
          - dialect: mariadb:10.3
          - dialect: mariadb:10.3.13
            platforms: linux/amd64
          - dialect: mariadb:10.7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build & Push ${{ matrix.dialect }} Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./.github/ops/mysql/Dockerfile
          push: true
          tags: arigaio/${{ matrix.dialect }}
          platforms: ${{ matrix.platforms || 'linux/amd64,linux/arm64' }}
          build-args: |
            DIALECT=${{ matrix.dialect }}
            ${{ matrix.build-args }}
