name: Push mysql quick boot images to Docker Hub
on:
  push:
    paths:
      - .github/ops/mysql/**
      - .github/workflows/cd-push-docker-mysql.yaml
    branches:
      - master
  schedule:
    # Runs at 00:00 on Sunday
    - cron: '0 0 * * 0'

jobs:
  push-docker:
    strategy:
      matrix:
        dialect: [ "mysql:latest", "mysql:5.6", "mysql:5.6.35", "mysql:5.7", "mysql:5.7.26", "mysql:8", "mariadb:latest", "mariadb:10.2", "mariadb:10.2.32", "mariadb:10.3", "mariadb:10.3.13", "mariadb:10.7"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & Push ${{ matrix.dialect }} Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./.github/ops/mysql/Dockerfile
          push: true
          tags: arigaio/${{ matrix.dialect }}
          build-args:
            DIALECT=${{ matrix.dialect }}