name: CD - Documentation Website
on:
  push:
    branches:
      - master
    paths:
      - 'doc/**'
      - '.github/workflows/cd-website_oss.yaml'
jobs:
  docs:
    name: deploy atlasgo.io
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./doc/website
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        run: npm install
      - name: Build website
        run: npm run build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy Website
        run: npm run upload
      - name: Invalidate Cache
        run: npm run invalidate-cdn
