name: Test Dev Container Features
on:
  push:
    branches:
      - master
    paths:
      - .devcontainer/features/**
      - .github/workflows/ci-devcontainer-features.yaml
  pull_request:
    paths:
      - .devcontainer/features/**
      - .github/workflows/ci-devcontainer-features.yaml
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        features:
          - cli
        baseImage:
          - mcr.microsoft.com/devcontainers/base:ubuntu
          - debian:bookworm
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: lts/*
      - name: Install latest devcontainer CLI
        run: npm install -g @devcontainers/cli
      - name: Test '${{ matrix.features }}' on '${{ matrix.baseImage }}'
        run: devcontainer features test ./.devcontainer/features -i ${{ matrix.baseImage }} -f ${{ matrix.features }}

  test-scenarios:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        features:
          - cli
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: lts/*
      - name: Install latest devcontainer CLI
        run: npm install -g @devcontainers/cli
      - name: Test scenarios for '${{ matrix.features }}'
        run: devcontainer features test ./.devcontainer/features --skip-autogenerated -f ${{ matrix.features }}
